services:
  ssl-server:
    build: .                  # was: /home/usi/scke/unified/
    platform: linux/arm64     # al3monni mod for arm porting
    container_name: Test-server
    networks:
      - openssl-net
    ports:
      - "5544:5544"
      - "5545:5545"
    restart: unless-stopped
    command: /app/server
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
      - CAP_NET_RAW
    privileged: true
    # DELETED: volumes: (/tmp/.X11-unix, ${HOME}/.Xauthority)
    # DELETED: environment: (DISPLAY=unix$DISPLAY)

networks:
  openssl-net:
    driver: bridge
